CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE TABLE contact_messages (
        "Id" uuid NOT NULL,
        "Name" character varying(120) NOT NULL,
        "Email" character varying(254) NOT NULL,
        "Subject" character varying(200) NOT NULL,
        "Message" character varying(4000) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedUtc" timestamptz NOT NULL,
        CONSTRAINT "PK_contact_messages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE TABLE projects (
        "Id" uuid NOT NULL,
        "Slug" character varying(120) NOT NULL,
        "Title" character varying(160) NOT NULL,
        "Summary" character varying(400) NOT NULL,
        "Description" text NOT NULL,
        "RepositoryUrl" character varying(500),
        "LiveUrl" character varying(500),
        "IsFeatured" boolean NOT NULL,
        "IsPublished" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "CreatedUtc" timestamptz NOT NULL,
        CONSTRAINT "PK_projects" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE TABLE technologies (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(80) NOT NULL,
        "Slug" character varying(80) NOT NULL,
        CONSTRAINT "PK_technologies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE TABLE project_technologies (
        "ProjectId" uuid NOT NULL,
        "TechnologyId" integer NOT NULL,
        CONSTRAINT "PK_project_technologies" PRIMARY KEY ("ProjectId", "TechnologyId"),
        CONSTRAINT "FK_project_technologies_projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES projects ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_project_technologies_technologies_TechnologyId" FOREIGN KEY ("TechnologyId") REFERENCES technologies ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE INDEX "IX_contact_messages_CreatedUtc" ON contact_messages ("CreatedUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE INDEX "IX_project_technologies_TechnologyId" ON project_technologies ("TechnologyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE INDEX "IX_projects_IsPublished_DisplayOrder" ON projects ("IsPublished", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_projects_Slug" ON projects ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_technologies_Name" ON technologies ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_technologies_Slug" ON technologies ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925135248_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260925135248_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

